[package]
name = "webkit_gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.16.0"
glib = "0.17.9"
gtk = "0.16.0"
javascriptcore-rs-sys = "1.0.0"
webkit2gtk = { version = "1.0.0", features = ["v2_6"] }
